apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: reddog.state.makeline
  namespace: reddog
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      secretKeyRef:
        name: redis-server
        key: redis-server
    - name: redisPassword
      secretKeyRef:
        name: redis-password
        key: redis-password
scopes:
  - make-line-service
auth:
  secretStore: reddog.secretstore 