apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: reddog  
  labels:
    name: ui
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: ui 
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: reddog
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "ui"
        dapr.io/app-port: "8080"
    spec:
      containers:
        - name: ui
          image: "ghcr.io/azure/reddog-retail-demo/reddog-retail-ui:latest"
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
          - name: VUE_APP_SITE_TITLE
            value: "Red Dog Pharmacy - Redmond"
          - name: VUE_APP_SITE_TYPE
            value: "Pharmacy"
          - name: VUE_APP_IS_CORP
            value: "false"
          - name: VUE_APP_STORE_ID
            value: "Redmond"
          - name: VUE_APP_MAKELINE_BASE_URL
            value: "http://localhost:3500/v1.0/invoke/make-line-service/method"
          - name: VUE_APP_ACCOUNTING_BASE_URL
            value: "http://localhost:3500/v1.0/invoke/accounting-service/method"